Repository wecode-bootcamp-korea/17-1st-StyleWe-backend, pull requests merged in 2021-02, with the labels that each got.

#1 [17기 남채린] models.py 작성
  config/settings.py
  feed/__init__.py
  feed/admin.py
  feed/apps.py
  feed/migrations/0001_initial.py
  feed/migrations/0002_auto_20210218_2028.py
  feed/migrations/__init__.py
  feed/models.py
  feed/tests.py
  feed/views.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210218_2028.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210218_2028.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: Accepted

#2 [17기 남채린] order/models.py에 날짜 속성 추가
  order/migrations/0003_auto_20210219_2003.py
  order/models.py
  product/migrations/0003_auto_20210219_2003.py
  user/migrations/0002_remove_adminlevel_brand.py
Labels: Status: 리뷰 요청

#4 [17기 남채린] product models.py 수정
  feed/migrations/0003_auto_20210220_2113.py
  feed/models.py
  product/migrations/0004_auto_20210220_1531.py
  product/models.py
  user/migrations/0003_auto_20210220_2113.py
  user/models.py
Labels: Status: Accepted

#5 [17기 남채린] feed models.py 수정
  feed/models.py
Labels: Status: 리뷰 요청

#8 [17기 남채린] user models 수정
  user/migrations/0004_auto_20210222_1726.py
  user/migrations/0005_auto_20210222_1728.py
  user/models.py
Labels: Status: 리뷰 요청

#3 [17기 심규보] SingInView 수정완료
  config/urls.py
  requirements.txt
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#9 [17기 남채린] user models 수정
  user/migrations/0006_auto_20210223_1505.py
  user/models.py
Labels: Status: 리뷰 요청

#7 [17기 심규보] SignUpInitializeView 수정완료
  config/urls.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: Accepted

#12 [17기 남채린] product models.py 수정
  order/migrations/0004_auto_20210224_1831.py
  order/models.py
  product/migrations/0005_auto_20210224_1726.py
  product/migrations/0006_auto_20210224_1831.py
  product/models.py
Labels: Status: Accepted

#13 [17기 심규보] SignInView Merge오류 이후 재 요청
  user/urls.py
  user/views.py
Labels: Status: Accepted

#11 [17기 남채린] FeedEntireView 생성
  config/urls.py
  feed/urls.py
  feed/views.py
Labels: Status: 리뷰 요청

#14 [17기 심규보] ProductView 생성
  config/urls.py
  product/urls.py
  product/views.py
  user/urls.py
Labels: Status: Accepted

#15 [17기 강승연] FeedDetailView 생성, user/utils.py 수정
  config/urls.py
  feed/urls.py
  feed/views.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 진행중
